# Generated by Django 4.1.7 on 2025-05-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="paradise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinema.paradise"
            ),
        ),
    ]
